//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yazilim_Mimarisi_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PROGRAM
    {
        public int PId { get; set; }
        public Nullable<int> PHasta { get; set; }
        public string Günler { get; set; }
        public string Sabah { get; set; }
        public string Ogle { get; set; }
        public string Aksam { get; set; }
    
        public virtual Tbl_HASTA Tbl_HASTA { get; set; }
    }
}
