//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yazilim_Mimarisi_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HASTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_HASTA()
        {
            this.Tbl_PROGRAM = new HashSet<Tbl_PROGRAM>();
        }
    
        public int HId { get; set; }
        public string HAd { get; set; }
        public string HSoyad { get; set; }
        public string HTC { get; set; }
        public Nullable<int> HHastalik { get; set; }
        public Nullable<int> HDiyet { get; set; }
        public Nullable<int> HDiyetisyen { get; set; }
    
        public virtual Tbl_DIYETISYEN Tbl_DIYETISYEN { get; set; }
        public virtual Tbl_DIYETLER Tbl_DIYETLER { get; set; }
        public virtual Tbl_HASTALIK Tbl_HASTALIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PROGRAM> Tbl_PROGRAM { get; set; }
    }
}
